#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop oss.service >/dev/null
  systemctl disable oss.service || true
  rm /var/log/thingsplex/oss/* || true
  rm /opt/thingsplex/oss/data/* || true
fi